name: Task 5 - Users, permissions and sudo report
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/task5-users-privileges-report.yml'
      - 'scripts/task5_users_privileges_report.sh'
      - 'scripts/build_pdf_report.py'
      - 'scripts/text_to_png.py'
jobs:
  build-report-task5:
    runs-on: ubuntu-latest
    env:
      REPORT_AUTHOR: Миленькова Ивана
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get update
          sudo apt-get install -y python3-pil sudo tcpdump
      - run: bash scripts/task5_users_privileges_report.sh
      - uses: actions/upload-artifact@v4
        with:
          name: task5-report-pdf
          path: reports/task5/report.pdf
