name: Task 9 - Environment variables report
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/task9-env-vars-report.yml'
      - 'scripts/task9_env_vars_report.sh'
      - 'scripts/build_pdf_report.py'
      - 'scripts/text_to_png.py'
jobs:
  build-report-task9:
    runs-on: ubuntu-latest
    env:
      REPORT_AUTHOR: Миленькова Ивана
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get update
          sudo apt-get install -y python3-pil
      - run: bash scripts/task9_env_vars_report.sh
      - uses: actions/upload-artifact@v4
        with:
          name: task9-report-pdf
          path: reports/task9/report.pdf
